-- CréeTonAgent, stage 1 schema (see docs/architecture/BACKEND_SYSTEM_DESIGN.md §6).
-- Billing tables (subscriptions, usage, payments) come in a later migration.

-- Every synced row carries `rev`, taken from one global sequence and bumped on
-- each insert/update. The app asks GET /v1/sync?cursor=<rev> for changes.
CREATE SEQUENCE rev_seq;

CREATE FUNCTION bump_rev() RETURNS trigger AS $$
BEGIN
  NEW.rev := nextval('rev_seq');
  NEW.updated_at := now();
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- Accounts --------------------------------------------------------------------

CREATE TABLE owners (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phone       text NOT NULL UNIQUE,              -- E.164, e.g. +2250748123390
  first_name  text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE otp_codes (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phone        text NOT NULL,
  code_hash    text NOT NULL,
  expires_at   timestamptz NOT NULL,
  attempts     int NOT NULL DEFAULT 0,
  consumed_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX otp_codes_phone_created ON otp_codes (phone, created_at DESC);

CREATE TABLE sessions (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id      uuid NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
  refresh_hash  text NOT NULL UNIQUE,
  device_name   text NOT NULL DEFAULT '',
  platform      text NOT NULL DEFAULT '',        -- ios | android | web
  push_token    text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_seen_at  timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL,
  revoked_at    timestamptz
);
CREATE INDEX sessions_owner ON sessions (owner_id);

-- Shop profile (BusinessProfile in the prototype) ------------------------------

CREATE TABLE shops (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id          uuid NOT NULL UNIQUE REFERENCES owners(id) ON DELETE CASCADE,
  name              text NOT NULL DEFAULT '',
  category          text CHECK (category IN ('restaurant', 'boutique')),
  location          text NOT NULL DEFAULT '',
  hours             text NOT NULL DEFAULT '',
  delivery_fee      text NOT NULL DEFAULT '',
  tiktok            text NOT NULL DEFAULT '',
  instagram         text NOT NULL DEFAULT '',
  facebook          text NOT NULL DEFAULT '',
  sales_channels    text[] NOT NULL DEFAULT '{}',
  service_modes     text[] NOT NULL DEFAULT '{}',
  delivery_zones    text[] NOT NULL DEFAULT '{}',
  payments          text[] NOT NULL DEFAULT '{}',
  tone              text NOT NULL DEFAULT 'amical' CHECK (tone IN ('formel', 'amical', 'ivoirien')),
  takeover_minutes  int NOT NULL DEFAULT 120 CHECK (takeover_minutes BETWEEN 5 AND 1440),
  rev               bigint NOT NULL DEFAULT nextval('rev_seq'),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER shops_rev BEFORE UPDATE ON shops FOR EACH ROW EXECUTE FUNCTION bump_rev();

CREATE TABLE catalog_items (
  id           uuid PRIMARY KEY,                    -- generated by the app
  shop_id      uuid NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  name         text NOT NULL,
  price_fcfa   int CHECK (price_fcfa >= 0),          -- null = « prix sur demande »
  available    boolean NOT NULL DEFAULT true,
  position     int NOT NULL DEFAULT 0,
  rev          bigint NOT NULL DEFAULT nextval('rev_seq'),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  deleted_at   timestamptz
);
CREATE INDEX catalog_items_shop ON catalog_items (shop_id);
CREATE TRIGGER catalog_items_rev BEFORE UPDATE ON catalog_items FOR EACH ROW EXECUTE FUNCTION bump_rev();

CREATE TABLE learned_answers (
  id               uuid PRIMARY KEY,                -- generated by the app
  shop_id          uuid NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  question         text NOT NULL,
  question_norm    text NOT NULL,                   -- normalize(question), for exact matches
  action           text NOT NULL CHECK (action IN ('catalog', 'price', 'delivery', 'payment', 'order', 'handoff', 'custom')),
  product_id       uuid,                            -- for action = 'price'
  answer           text NOT NULL DEFAULT '',        -- for action = 'custom'
  source           text NOT NULL CHECK (source IN ('manual', 'correction')),
  from_message_id  uuid,
  rev              bigint NOT NULL DEFAULT nextval('rev_seq'),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  deleted_at       timestamptz
);
CREATE INDEX learned_answers_shop_norm ON learned_answers (shop_id, question_norm) WHERE deleted_at IS NULL;
CREATE TRIGGER learned_answers_rev BEFORE UPDATE ON learned_answers FOR EACH ROW EXECUTE FUNCTION bump_rev();

-- WhatsApp ----------------------------------------------------------------------

CREATE TABLE channels (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id          uuid NOT NULL UNIQUE REFERENCES shops(id) ON DELETE CASCADE,
  provider         text NOT NULL DEFAULT 'meta_cloud' CHECK (provider IN ('meta_cloud')),
  phone_number_id  text NOT NULL UNIQUE,            -- Meta's id of the WhatsApp number
  display_phone    text NOT NULL DEFAULT '',
  status           text NOT NULL DEFAULT 'connected' CHECK (status IN ('connected', 'disconnected')),
  connected_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE customers (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id        uuid NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  wa_id          text NOT NULL,                     -- customer's WhatsApp id (phone digits)
  display_name   text NOT NULL DEFAULT '',
  first_seen_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (shop_id, wa_id)
);

CREATE TABLE conversations (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id                   uuid NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  customer_id               uuid NOT NULL UNIQUE REFERENCES customers(id) ON DELETE CASCADE,
  last_message_at           timestamptz NOT NULL DEFAULT now(),
  last_customer_message_at  timestamptz,           -- WhatsApp's 24-hour reply window
  ai_paused_until           timestamptz,           -- « Je prends la main »
  needs_attention           boolean NOT NULL DEFAULT false,
  unread_count              int NOT NULL DEFAULT 0,
  rev                       bigint NOT NULL DEFAULT nextval('rev_seq'),
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX conversations_shop_last ON conversations (shop_id, last_message_at DESC);
CREATE TRIGGER conversations_rev BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION bump_rev();

CREATE TABLE messages (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id          uuid NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  conversation_id  uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role             text NOT NULL CHECK (role IN ('customer', 'assistant', 'owner')),
  kind             text NOT NULL DEFAULT 'text',    -- text | audio | image | video | sticker | document | location | other
  text             text NOT NULL DEFAULT '',
  wamid            text UNIQUE,                     -- WhatsApp message id: dedupes webhook retries
  client_id        uuid UNIQUE,                     -- app-generated id: makes owner sends retry-safe
  status           text NOT NULL DEFAULT 'received'
                     CHECK (status IN ('received', 'queued', 'sent', 'delivered', 'read', 'failed')),
  engine           jsonb,                           -- action, source, model, tokens… for assistant replies
  error            text,
  rev              bigint NOT NULL DEFAULT nextval('rev_seq'),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX messages_conversation_created ON messages (conversation_id, created_at);
CREATE INDEX messages_shop_rev ON messages (shop_id, rev);
CREATE TRIGGER messages_rev BEFORE UPDATE ON messages FOR EACH ROW EXECUTE FUNCTION bump_rev();

CREATE TABLE alerts (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id          uuid NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  conversation_id  uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  message_id       uuid REFERENCES messages(id) ON DELETE SET NULL,
  kind             text NOT NULL CHECK (kind IN ('order', 'question')),
  summary          text NOT NULL,
  status           text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  pushed_at        timestamptz,
  seen_at          timestamptz,
  resolved_at      timestamptz,
  rev              bigint NOT NULL DEFAULT nextval('rev_seq'),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
-- At most one open alert per conversation: a new one updates it instead.
CREATE UNIQUE INDEX alerts_one_open_per_conversation ON alerts (conversation_id) WHERE status = 'open';
CREATE INDEX alerts_shop_rev ON alerts (shop_id, rev);
CREATE TRIGGER alerts_rev BEFORE UPDATE ON alerts FOR EACH ROW EXECUTE FUNCTION bump_rev();

-- Operations --------------------------------------------------------------------

-- Raw webhook payloads, kept to replay or debug real traffic.
CREATE TABLE webhook_events (
  id            bigserial PRIMARY KEY,
  source        text NOT NULL,                     -- meta
  payload       jsonb NOT NULL,
  received_at   timestamptz NOT NULL DEFAULT now(),
  processed_at  timestamptz,
  error         text
);

-- Job queue in Postgres. `key` makes a job unique while it waits, so enqueuing
-- the same key again pushes the existing job back (debounce) instead of adding
-- a second one. The key is cleared when a worker picks the job up.
CREATE TABLE jobs (
  id            bigserial PRIMARY KEY,
  kind          text NOT NULL,
  key           text UNIQUE,
  payload       jsonb NOT NULL DEFAULT '{}',
  run_at        timestamptz NOT NULL DEFAULT now(),
  attempts      int NOT NULL DEFAULT 0,
  max_attempts  int NOT NULL DEFAULT 5,
  locked_at     timestamptz,
  locked_by     text,
  last_error    text,
  failed_at     timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jobs_ready ON jobs (run_at) WHERE locked_at IS NULL AND failed_at IS NULL;
